const DEFAULT_RECIPES = [
  {
    id: 1,
    title: 'Rolls Chapati (Roti)',
    description:
      'A delicious Indian flatbread roll filled with flavorful stuffing. Perfect for lunch or dinner.',
    ingredients: [
      'Wheat flour (1 cup)',
      'Water (as needed)',
      'Salt to taste',
      'Chilli powder',
      'Coriander powder',
      'Onion (chopped)',
      'Chat masala',
      'Tomato (chopped)',
      'Paneer (optional)',
      'Oil for cooking',
    ],
    steps: [
      'Take equal amount of wheat flour and water and start mixing to form a dough',
      'Make sure the dough is not too thin or thick, just enough to make chapati',
      'Add salt and spices to the dough to make it taste better',
      'Prepare the stuffing by chopping onion, tomato, and paneer into small pieces',
      'Heat oil in a pan and add the chopped ingredients',
      'Add spices and cook until everything is well combined',
      'Roll the dough into chapati and cook on a heated pan',
      'Once the chapati is almost ready, spread the stuffing mixture on it',
      'Roll the chapati with the stuffing inside',
      'Heat it once again on the pan and your roll is ready to serve',
    ],
    prepTime: 20,
    cookTime: 25,
    difficulty: 'medium',
    imageUrl:
      'https://c.ndtvimg.com/2020-01/nqphvs18_kathi-roll_625x300_17_January_20.jpg',
  },
  {
    id: 2,
    title: 'Egg Maggi',
    description:
      'A quick and delicious twist on instant noodles with eggs and vegetables. Perfect comfort food!',
    ingredients: [
      'Maggi noodles (2 packets)',
      'Water (850 ml)',
      'Salt to taste',
      'Chillis (3-4, cut into small pieces)',
      'Maggi masala (2 packets)',
      'Eggs (2)',
      'Onion (chopped small)',
      'Oil (1/2 tablespoon)',
      'Extra salt (1/2 tablespoon for egg)',
    ],
    steps: [
      'Turn on the heating source (electric induction or gas) and put a pan on it',
      'Pour 850 ml of water in the pan and let it boil',
      'When water starts boiling, put the Maggi noodles into the boiling water',
      'Cook for 3-4 minutes until Maggi becomes soft',
      'When bubbles start appearing, add the masala from the Maggi packet',
      'Watch the Maggi change color from white to orangish color',
      'Put the pan off the heating source and turn off the heat',
      'For the egg preparation: Put 1/2 tablespoon oil in another pan',
      'Add chopped onion and small pieces of chilli to the pan',
      'Spread the onion in circular direction and let it cook for a minute or two',
      'Take a bowl, break eggs ensuring the shell is not falling in your dish',
      'Pour the eggs in the center of the pan over the onion mixture',
      'Add salt (1/2 tablespoon) and spread it inside the pan in circular direction',
      'Let the omelette start taking shape, then flip it in the pan',
      'Let the other side cook, then cut it into small vertical and horizontal pieces',
      'Serve the Maggi in a bowl with the egg mixture on top',
      'Mix it well and enjoy with fork and spoon',
    ],
    prepTime: 10,
    cookTime: 15,
    difficulty: 'easy',
    imageUrl:
      'https://images.raasakarts.com/insecure/fit/1000/1000/ce/0/plain/https://rasakart-assets.s3.ap-south-1.amazonaws.com/3fa229/prods/obfu9Dkd2PV8A1GnRuXWYIDKX6B3EpSHSmltActZ.jpg@webp',
  },
  {
    id: 3,
    title: 'Classic Pasta Carbonara',
    description:
      'Creamy Italian pasta with bacon, eggs, and parmesan cheese. A restaurant-quality dish at home.',
    ingredients: [
      'Spaghetti (400g)',
      'Bacon (200g, diced)',
      'Eggs (4 large)',
      'Parmesan cheese (1 cup, grated)',
      'Black pepper (freshly ground)',
      'Salt to taste',
      'Garlic (2 cloves, minced)',
      'Olive oil (2 tablespoons)',
    ],
    steps: [
      'Bring a large pot of salted water to boil',
      'Cook spaghetti according to package directions until al dente',
      'While pasta cooks, fry bacon in a large pan until crispy',
      'Add minced garlic and cook for 1 minute',
      'In a bowl, whisk together eggs and parmesan cheese',
      'Reserve 1 cup of pasta water, then drain the pasta',
      'Add hot pasta to the bacon pan and toss',
      'Remove from heat and quickly stir in egg mixture',
      'Add pasta water gradually to achieve creamy consistency',
      'Season with black pepper and serve immediately',
    ],
    prepTime: 10,
    cookTime: 20,
    difficulty: 'medium',
    imageUrl:
      'https://www.gogogogourmet.com/wp-content/uploads/2015/06/Carbonara-1024x669.jpg',
  },
  {
    id: 4,
    title: 'Chicken Tikka Masala',
    description:
      'Tender chicken pieces in a rich, creamy tomato-based curry. A beloved Indian restaurant classic.',
    ingredients: [
      'Chicken breast (500g, cubed)',
      'Yogurt (1 cup)',
      'Tikka masala spice (2 tablespoons)',
      'Tomato puree (400g)',
      'Heavy cream (1 cup)',
      'Onion (2, finely chopped)',
      'Ginger-garlic paste (2 tablespoons)',
      'Garam masala (1 teaspoon)',
      'Butter (3 tablespoons)',
      'Salt to taste',
      'Fresh coriander for garnish',
    ],
    steps: [
      'Marinate chicken with yogurt and tikka masala spice for 30 minutes',
      'Heat butter in a pan and add chopped onions',
      'Cook onions until golden brown',
      'Add ginger-garlic paste and cook for 2 minutes',
      'Add marinated chicken and cook until slightly charred',
      'Add tomato puree and cook for 10 minutes',
      'Stir in heavy cream and garam masala',
      'Simmer for 15 minutes until chicken is cooked through',
      'Adjust seasoning with salt',
      'Garnish with fresh coriander and serve with rice or naan',
    ],
    prepTime: 40,
    cookTime: 35,
    difficulty: 'medium',
    imageUrl:
      'https://ministryofcurry.com/wp-content/uploads/2025/04/chicken-tikka-masala_-5.jpg',
  },
  {
    id: 5,
    title: 'Chocolate Chip Cookies',
    description:
      'Soft, chewy homemade cookies loaded with chocolate chips. Perfect for dessert or snacking.',
    ingredients: [
      'All-purpose flour (2 1/4 cups)',
      'Butter (1 cup, softened)',
      'Brown sugar (3/4 cup)',
      'White sugar (3/4 cup)',
      'Eggs (2)',
      'Vanilla extract (2 teaspoons)',
      'Baking soda (1 teaspoon)',
      'Salt (1 teaspoon)',
      'Chocolate chips (2 cups)',
    ],
    steps: [
      'Preheat oven to 375°F (190°C)',
      'Cream together butter, brown sugar, and white sugar',
      'Beat in eggs one at a time, then add vanilla',
      'In separate bowl, combine flour, baking soda, and salt',
      'Gradually blend dry ingredients into butter mixture',
      'Stir in chocolate chips',
      'Drop rounded tablespoons of dough onto ungreased cookie sheets',
      'Bake for 9-11 minutes or until golden brown',
      'Cool on baking sheet for 2 minutes',
      'Transfer to wire rack to cool completely',
    ],
    prepTime: 15,
    cookTime: 11,
    difficulty: 'easy',
    imageUrl:
      'https://www.allrecipes.com/thmb/dNzzgeEyacuH-RIfMI4PjWFODBM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-9996-chewy-peanut-butter-chocolate-chip-cookies-ddmfs-4x3-614164ea044a4845b3cca7e725ecf7bd.jpg',
  },
];
